/* ===== Rozšířená knihovna cviků =====
   Obecná knihovna nad rámec plánu od trenéra — náhrady, když je stroj obsazený,
   a doplňky pro dny mimo plán. Popis je vždy technika a častá chyba, ne série
   a opakování: programování patří trenérovi, ne appce.

   Formát: [id, název, partie, popis]
   Migrace běží jednou přes flag exerciseDbV1 v data.js — vlastní cviky se
   stejným názvem zůstávají nedotčené. */
"use strict";

const EXERCISE_DB = [

  /* ---------- Hrudník ---------- */
  ["xd-bench-incline", "Bench press na šikmé lavici", "Hrudník",
    "Lavice 30–45°, osu spouštěj ke klíčním kostem, ne k bradě. Vyšší úhel přenáší práci do předních delt."],
  ["xd-bench-decline", "Bench press na negativní lavici", "Hrudník",
    "Zaměřuje spodní část prsou. Nohy pevně zaklesnuté, osu spouštěj k dolnímu okraji hrudníku."],
  ["xd-db-press-flat", "Tlaky s jednoručkami na rovné lavici", "Hrudník",
    "Větší rozsah než velká činka a každá strana pracuje sama. Dole nezastavuj v úplném protažení, drž tlak v prsou."],
  ["xd-db-fly-incline", "Rozpažky s jednoručkami na šikmé lavici", "Hrudník",
    "Lokty mírně pokrčené a po celou dobu ve stejném úhlu — objímáš strom, netlačíš. Dole jdi jen do příjemného protažení."],
  ["xd-pushup-feet-up", "Kliky s nohama na vyvýšení", "Hrudník",
    "Čím výš nohy, tím víc práce pro horní hrudník a ramena. Tělo drž v jedné přímce, pánev nepovoluj."],
  ["xd-pushup-diamond", "Kliky s úzkým úchopem", "Hrudník",
    "Ruce pod hrudníkem, palce a ukazováky se dotýkají. Lokty veď podél těla — zabírá vnitřní hrudník a triceps."],
  ["xd-pullover-db", "Pullover s jednoručkou vleže", "Hrudník",
    "Vleže přes lavici nebo podél. Jednoručku veď nad hlavu s mírně pokrčenými lokty, tah cítíš v prsou a širokém svalu."],
  ["xd-crossover-high", "Křížení kladek shora", "Hrudník",
    "Kladky nad hlavou, ruce veď dolů a dopředu ke pupku. Dole zmáčkni prsa k sobě a chvíli drž."],
  ["xd-crossover-low", "Křížení kladek zespodu", "Hrudník",
    "Kladky u země, ruce veď nahoru a dopředu jako při rozpažení vzhůru. Míří na horní část prsou."],
  ["xd-pecdeck", "Rozpažky na stroji (pec deck)", "Hrudník",
    "Zádová opěrka pevně na lopatkách, lokty ve výšce ramen. Vracej pomalu, konec pohybu neházej."],

  /* ---------- Záda ---------- */
  ["xd-pullup-under", "Shyby podhmatem", "Záda",
    "Podhmat zapojí biceps víc než nadhmat. Vytáhni lopatky dolů dřív, než začneš táhnout loktem."],
  ["xd-pullup-wide", "Shyby širokým úchopem", "Záda",
    "Širší úchop míří na šířku zad. Nedělej trhavé kmitání — když nedáš rozsah, použij gumu nebo stroj s dopomocí."],
  ["xd-db-row-one", "Přítahy jednoručky v předklonu", "Záda",
    "Jedna ruka o lavici, záda rovná. Loket veď dozadu k boku, ne do strany. Dole nechej lopatku dojít dopředu."],
  ["xd-tbar-row", "Přítahy T-bar", "Záda",
    "Trup nad 45°, hrudník vypnutý. Táhni k pupku a nahoře stáhni lopatky — bederní páteř nezakulacuj."],
  ["xd-latpull-under", "Stahování horní kladky podhmatem", "Záda",
    "Podhmat táhne lokty víc k tělu a zabírá spodní vlákna. Trup drž jen mírně vzadu, nekmitej."],
  ["xd-latpull-one", "Stahování horní kladky jednoručně", "Záda",
    "Jedna ruka umožní větší rozsah a srovná stranové rozdíly. Druhou rukou se drž, ale netahej s ní."],
  ["xd-machine-row", "Přítahy na stroji v předklonu", "Záda",
    "Hrudník o opěrku, lokty veď dozadu podél těla. Stroj drží dráhu, takže můžeš jít blíž k selhání."],
  ["xd-cable-pullover", "Pullover na horní kladce", "Záda",
    "Stoj v mírném předklonu, paže téměř napnuté. Táhni obloukem k bokům — izoluje široký sval bez zapojení bicepsu."],
  ["xd-inverted-row", "Přítahy v podporu ležmo", "Záda",
    "Osu nastav do pasu, tělo v přímce. Čím vodorovnější tělo, tím těžší. Hrudník doveď až k ose."],
  ["xd-deadlift-db", "Mrtvý tah s jednoručkami", "Záda",
    "Šetrnější k bedrům než velká činka. Jednoručky veď podél stehen, pánev vyklápěj dozadu, kolena jen mírně pokrč."],
  ["xd-hyperext", "Hyperextenze", "Záda",
    "Podložka pod kyčelními kostmi, ne pod žebry. Nahoru jen do přímky — přehnutí do záklonu bedra netrénuje, jen dráždí."],
  ["xd-good-morning", "Good morning", "Záda",
    "Osa na trapézech, kolena mírně pokrčená. Předklon vede pánev, ne páteř. Začni s velmi lehkou vahou."],
  ["xd-shrug-bar", "Shrugy s velkou činkou", "Záda",
    "Jen vytažení ramen k uším, žádná rotace. Nahoře chvíli drž, dolů pouštěj kontrolovaně."],
  ["xd-shrug-db", "Shrugy s jednoručkami", "Záda",
    "Jednoručky podél těla umožní vyšší rozsah než osa vpředu. Hlavu drž v ose, nepředsouvej ji."],
  ["xd-cable-row-one", "Přítahy spodní kladky jednoručně", "Záda",
    "Umožní rotaci trupu a delší tah. Na konci nech lopatku dojít dopředu, pak zataž zpět."],

  /* ---------- Nohy ---------- */
  ["xd-front-squat", "Dřep s činkou vpředu", "Nohy",
    "Osa na předních deltách, lokty vysoko. Drží trup vzpřímeněji než zadní dřep, takže víc zabírají kvadricepsy."],
  ["xd-goblet-squat", "Goblet dřep", "Nohy",
    "Jednoručka nebo kettlebell u hrudníku. Nejlepší volba na naučení hloubky — závaží vpředu drží trup vzpřímený."],
  ["xd-hack-squat", "Hack dřep", "Nohy",
    "Záda po celé délce na opěrce, chodidla vyšší než pánev. Kolena vedou dopředu, ale nepřepínej je nahoře."],
  ["xd-sumo-squat", "Sumo dřep", "Nohy",
    "Široký postoj, špičky ven. Kolena tlač nad špičky, zabírají vnitřní stehna a hýždě."],
  ["xd-legpress-one", "Leg press jednonož", "Nohy",
    "Srovná stranové rozdíly a přidá rozsah. Chodidlo doprostřed plotny, koleno nepropínej."],
  ["xd-leg-curl-seated", "Zakopávání v sedě", "Nohy",
    "Sed zapojí hamstringy v jiné délce než leh — oba varianty se doplňují. Podložka nad kolenem, ne na něm."],
  ["xd-leg-curl-standing", "Zakopávání ve stoje jednonož", "Nohy",
    "Stojnou nohu drž mírně pokrčenou, pánev nevytáčej. Pohyb dělá jen koleno."],
  ["xd-leg-ext-one", "Předkopávání jednonož", "Nohy",
    "Odhalí rozdíl mezi stranami, který obounož zmizí. Nahoře chvíli drž a povol pomalu."],
  ["xd-lunge-back", "Výpady vzad", "Nohy",
    "Šetrnější ke kolenům než výpady vpřed. Krok vzad, koleno spouštěj k zemi, trup vzpřímený."],
  ["xd-lunge-walk", "Výpady do chůze", "Nohy",
    "Krok následuje krok bez zastavení. Delší krok zapojí hýždě, kratší kvadricepsy."],
  ["xd-step-up", "Výstupy na bednu", "Nohy",
    "Bedna do výše kolena. Nahoru táhne horní noha — dolní se neodráží. Dolů pomalu, ne seskokem."],
  ["xd-nordic-curl", "Nordic curl", "Nohy",
    "Kotníky zafixované, tělo spouštěj vpřed jen tak daleko, jak ho udržíš. Nejtvrdší cvik na hamstringy, začni s dopomocí rukou."],
  ["xd-calf-seated", "Výpony v sedě", "Nohy",
    "Pokrčené koleno zapojí spodní lýtkový sval. Dole nech patu klesnout do protažení, nahoře vydrž."],
  ["xd-calf-legpress", "Výpony na leg pressu", "Nohy",
    "Špičky na spodním okraji plotny, kolena mírně pokrčená. Plný rozsah je důležitější než váha."],
  ["xd-hip-abduction", "Abdukce kyčle na stroji", "Nohy",
    "Roznožování zabírá střední hýžďový sval. Trup mírně předkloněný přidá zapojení, netlač zády do opěrky."],
  ["xd-hip-adduction", "Addukce kyčle na stroji", "Nohy",
    "Snožování na vnitřní stehna. Pohyb veď kolenem, ne kotníkem, a vracej pomalu."],
  ["xd-deadlift-sumo", "Mrtvý tah sumo", "Nohy",
    "Široký postoj, ruce mezi koleny. Kratší dráha a menší nárok na bedra než klasický tah, víc práce pro hýždě a vnitřní stehna."],
  ["xd-sissy-squat", "Sissy dřep", "Nohy",
    "Kolena jdou dopředu, pánev zůstává v ose s trupem. Protahuje kvadricepsy v maximální délce — jdi jen do rozsahu bez bolesti kolen."],
  ["xd-glute-kickback", "Zanožování na kladce", "Nohy",
    "Manžeta na kotník, trup zpevněný. Pohyb končí v ose těla — přehnutí do záklonu jde do bederní páteře, ne do hýždí."],

  /* ---------- Ramena ---------- */
  ["xd-arnold-press", "Arnold press", "Ramena",
    "Start s jednoručkami před tělem podhmatem, během tlaku rotuj do nadhmatu. Rotace projde celým rozsahem předních delt."],
  ["xd-ohp-machine", "Tlaky nad hlavu na stroji", "Ramena",
    "Dráha je dána, takže se dá jít blíž k selhání bez hlídání stability. Zádovou opěrku nastav tak, aby ruce šly podél uší."],
  ["xd-ohp-seated-bar", "Tlaky nad hlavu v sedě s velkou činkou", "Ramena",
    "Sed s oporou drží bedra. Osu veď před hlavou, hlavu jen mírně předsuň — za hlavu netlač, je to nepřirozený úhel."],
  ["xd-lat-raise-cable", "Upažování na kladce", "Ramena",
    "Kladka u země za tělem drží tah po celém rozsahu, na rozdíl od jednoručky. Loket veď mírně pokrčený a výš než zápěstí."],
  ["xd-lat-raise-machine", "Upažování na stroji", "Ramena",
    "Podložky na vnější straně paží, nikoliv v rukách. Stroj drží úhel, takže střední delty pracují bez švihu."],
  ["xd-front-raise-db", "Předpažování s jednoručkami", "Ramena",
    "Do výše očí, palce mírně vzhůru. Nekmitej trupem — když musíš, je váha vysoká."],
  ["xd-front-raise-plate", "Předpažování s kotoučem", "Ramena",
    "Kotouč drž po stranách jako volant. Rovnoměrné zatížení obou rukou a snadné dávkování váhy."],
  ["xd-rear-fly-db", "Rozpažování v předklonu", "Ramena",
    "Předklon do vodorovné polohy, hrudník vypnutý. Lokty veď do strany a mírně vzad — zadní delty, ne trapézy."],
  ["xd-reverse-pecdeck", "Reverse pec deck", "Ramena",
    "Hrudník o opěrku, paže téměř napnuté. Vzadu zmáčkni lopatky k sobě a pomalu povol."],
  ["xd-upright-row", "Přítahy k bradě", "Ramena",
    "Úchop na šíři ramen, lokty vedou vzhůru. Táhni jen do výše hrudníku — výš už tlačí rameno do nepříjemné rotace."],
  ["xd-rear-delt-cable", "Zadní delty na kladce jednoručně", "Ramena",
    "Kladka ve výši ramen, tah vede přes tělo do strany a vzad. Loket drž ve stejné výšce jako rameno."],
  ["xd-landmine-press", "Landmine press", "Ramena",
    "Osa v držáku u země, tlak vede diagonálně vzhůru. Úhel je šetrnější k ramenům než tlak přímo nad hlavu."],

  /* ---------- Biceps ---------- */
  ["xd-curl-ez", "Bicepsový zdvih s EZ osou", "Biceps",
    "Lomená osa zmírní tah na zápěstí. Lokty drž u těla, nekmitej pánví."],
  ["xd-curl-cable", "Bicepsový zdvih na kladce", "Biceps",
    "Kladka drží tah i v dolní části pohybu, kde jednoručka odlehčí. Loket zůstává na místě."],
  ["xd-curl-concentration", "Koncentrovaný zdvih", "Biceps",
    "V sedě loket o vnitřní stranu stehna. Nejlepší izolace bicepsu — váha je vedlejší, rozsah hlavní."],
  ["xd-curl-bayesian", "Zdvihy na kladce v předklonu", "Biceps",
    "Stojíš čelem od kladky, paže za tělem. Biceps pracuje v protažené délce, kde jinak dostane nejméně."],
  ["xd-curl-incline", "Zdvihy s jednoručkami na šikmé lavici", "Biceps",
    "Záklon protáhne dlouhou hlavu bicepsu. Paže nechej volně viset, nepřitahuj lokty dopředu."],
  ["xd-curl-spider", "Spider curl", "Biceps",
    "Hrudník o šikmou lavici, paže svisle dolů. Odstraní švih úplně — cítíš jen biceps."],
  ["xd-curl-reverse", "Zdvihy obráceným úchopem", "Biceps",
    "Nadhmat zapojí sval na vrchní straně předloktí. Váhy budou nižší než u podhmatu, to je normální."],
  ["xd-wrist-curl", "Zdvihy zápěstí", "Biceps",
    "Předloktí o lavici, pohyb dělá jen zápěstí. Pomáhá s úchopem na mrtvý tah a shyby."],
  ["xd-preacher-machine", "Preacher curl na stroji", "Biceps",
    "Paže na šikmé podložce, lokty pevně. Nahoře nepovoluj tah, dole jdi do plného napnutí."],
  ["xd-curl-hammer-rope", "Hammer curl na kladce s lanem", "Biceps",
    "Neutrální úchop na lano míří na brachialis pod bicepsem. Lokty u těla, konce lana rozevři."],

  /* ---------- Triceps ---------- */
  ["xd-pushdown-rope", "Stahování kladky s lanem", "Triceps",
    "Dole konce lana rozevři a otoč palce dolů — přidá to poslední kus stahu. Lokty zůstávají u boků."],
  ["xd-pushdown-reverse", "Stahování kladky obráceným úchopem", "Triceps",
    "Podhmat míří na vnitřní hlavu tricepsu. Zápěstí drž zpevněné, ne zalomené."],
  ["xd-overhead-cable", "Tlaky nad hlavu na kladce", "Triceps",
    "Čelem od kladky, paže nad hlavou. Protažená pozice zabírá dlouhou hlavu, kterou stahování dolů míjí."],
  ["xd-overhead-db", "Francouzský tlak s jednoručkou nad hlavou", "Triceps",
    "Jedna jednoručka oběma rukama nebo každá zvlášť. Lokty drž blízko hlavy a nerozevírej je do strany."],
  ["xd-kickback-db", "Kickback s jednoručkou", "Triceps",
    "Předklon, paže v ose trupu, pohyb dělá jen předloktí. Nahoře napni a chvíli drž."],
  ["xd-kickback-cable", "Kickback na kladce", "Triceps",
    "Kladka drží tah i nahoře, kde jednoručka odlehčí. Loket zafixuj vedle trupu."],
  ["xd-close-grip-bench", "Bench press úzkým úchopem", "Triceps",
    "Úchop na šíři ramen, ne užší — jinak trpí zápěstí. Lokty veď podél těla, osu spouštěj k dolním žebrům."],
  ["xd-bench-dips", "Kliky na lavici", "Triceps",
    "Ruce na lavici za tělem, nohy vpředu. Rameno nepouštěj dolů do bolesti — jdi jen do 90° v lokti."],
  ["xd-triceps-machine", "Tlaky na tricepsovém stroji", "Triceps",
    "Dráha je dána, takže lze jít blíž k selhání. Sed nastav tak, aby lokty byly v ose s osou stroje."],
  ["xd-skullcrusher", "Skull crushers s EZ osou vleže", "Triceps",
    "Osu spouštěj za hlavu, ne na čelo — drží to tah v tricepsu po celém rozsahu. Lokty nerozevírej."],

  /* ---------- Core ---------- */
  ["xd-side-plank", "Boční plank", "Core",
    "Loket pod ramenem, tělo v přímce od hlavy k patám. Pánev nepouštěj dolů, boční břicho drž zpevněné."],
  ["xd-plank-reach", "Plank s přenosem váhy", "Core",
    "Z planku střídavě natahuj ruku dopředu. Pánev se nesmí otáčet — to je ta práce, ne délka výdrže."],
  ["xd-cable-crunch", "Zkracovačky na kladce", "Core",
    "V kleku, lano za hlavou. Pohyb dělá kulacení hrudní páteře, ne přítah pánve. Vydechni na konci stahu."],
  ["xd-crunch-machine", "Zkracovačky na stroji", "Core",
    "Umožní přidávat váhu progresivně, což u zkracovaček na zemi nejde. Vracej se pomalu."],
  ["xd-russian-twist", "Ruské rotace", "Core",
    "V sedě, nohy nad zemí, závaží před hrudníkem. Rotaci vede trup, ne ruce."],
  ["xd-pallof-press", "Pallof press", "Core",
    "Bokem ke kladce, ruce od hrudníku dopředu. Cvik proti rotaci — úkol je nepovolit, ne se hýbat."],
  ["xd-hollow-hold", "Hollow hold", "Core",
    "Bedra přitisknutá k zemi, ramena i nohy nad zemí. Když se bedra odlepí, zkrať páku — pokrč kolena."],
  ["xd-leg-raise-floor", "Zvedání nohou vleže", "Core",
    "Pánev podsazená, bedra na zemi. Dolů jen tak nízko, jak udržíš bedra přitisknutá."],
  ["xd-captains-chair", "Zvedání nohou v podporu", "Core",
    "Předloktí na podložkách, tělo svisle. Kolena k hrudníku s podsazenou pánví — nekmitej."],
  ["xd-bicycle-crunch", "Kolo", "Core",
    "Střídavě loket ke protilehlému koleni. Pomalu — rychlost mění cvik na kmitání."],
  ["xd-ab-wheel", "Ab wheel", "Core",
    "Z kleku roluj dopředu jen tak daleko, jak udržíš podsazenou pánev. Bedra se nesmí prohnout."],
  ["xd-woodchopper", "Dřevorubec na kladce", "Core",
    "Diagonální tah od horní kladky k protilehlému boku. Pohyb vede rotace trupu, paže jsou jen spojka."],
  ["xd-hanging-knee-raise", "Kolena k hrudi ve visu", "Core",
    "Lehčí varianta zvedání nohou. Podsaď pánev a táhni kolena nad úroveň pasu, ne jen do 90°."],
  ["xd-v-up", "V-up", "Core",
    "Současně zvedni nohy i trup do V. Když nedáš rozsah, dělej střídavě jednu nohu."]
];

/* ===== Anglické názvy cviků =====
   Druhý řádek pod českým názvem — kvůli hledání videí, čtení zahraničních
   zdrojů a domluvě v posilovně. Mapa pokrývá i cviky ze seedExercises()
   a z plánu trenéra, proto je klíčovaná podle id, ne podle názvu.
   Vlastní cviky uživatele tu nejsou a druhý řádek se u nich nezobrazí. */
const EXERCISE_NAME_EN = {
  /* --- seedExercises --- */
  "ex-bench": "Barbell bench press",
  "ex-incdb": "Incline dumbbell press",
  "ex-fly": "Cable fly",
  "ex-pushup": "Push-up",
  "ex-deadlift": "Deadlift",
  "ex-row": "Barbell bent-over row",
  "ex-latpull": "Lat pulldown",
  "ex-cablerow": "Seated cable row",
  "ex-pullup": "Pull-up",
  "ex-squat": "Back squat",
  "ex-legpress": "Leg press",
  "ex-rdl": "Romanian deadlift",
  "ex-lunge": "Lunge",
  "ex-calf": "Standing calf raise",
  "ex-ohp": "Overhead press",
  "ex-latraise": "Dumbbell lateral raise",
  "ex-facepull": "Face pull",
  "ex-curl": "Barbell curl",
  "ex-hammer": "Hammer curl",
  "ex-pushdown": "Triceps pushdown",
  "ex-skull": "Skull crusher",
  "ex-dips": "Parallel bar dip",
  "ex-plank": "Plank",
  "ex-legraise": "Hanging leg raise",
  "ex-crunch": "Crunch",

  /* --- plán trenéra --- */
  "cp-a1": "Dead bug + plank hold",
  "cp-a2": "Squat / Lunge / Duck walk",
  "cp-a3": "Leg press",
  "cp-a4": "Lying leg curl",
  "cp-a5": "Lat pulldown",
  "cp-a6": "Smith machine bench press",
  "cp-a7": "Reverse pec deck",
  "cp-a8": "Dumbbell curl",
  "cp-a9": "Assisted dip",
  "cp-b1": "Leg raise",
  "cp-b2": "Leg extension",
  "cp-b3": "Pendulum squat",
  "cp-b4": "Machine hip thrust",
  "cp-b5": "Reclined pec deck",
  "cp-b6": "Seated row",
  "cp-b7": "Incline EZ-bar skull crusher",
  "cp-b8": "Three-way delt raise",
  "cp-b9": "Preacher curl",
  "cp-c1": "Medicine ball abs + plank kettlebell drag",
  "cp-c2": "Bulgarian split squat",
  "cp-c3": "Belt squat Romanian deadlift",
  "cp-c4": "Dumbbell shoulder press",
  "cp-c5": "Kneeling machine row",
  "cp-c6": "Machine chest press",
  "cp-c7": "Cable skier + triceps pushdown",
  "cp-c8": "Cable hammer curl",
  "cp-c9": "Dumbbell lateral raise",

  /* --- rozšířená knihovna: hrudník --- */
  "xd-bench-incline": "Incline barbell bench press",
  "xd-bench-decline": "Decline barbell bench press",
  "xd-db-press-flat": "Flat dumbbell press",
  "xd-db-fly-incline": "Incline dumbbell fly",
  "xd-pushup-feet-up": "Decline push-up",
  "xd-pushup-diamond": "Diamond push-up",
  "xd-pullover-db": "Dumbbell pullover",
  "xd-crossover-high": "High-to-low cable crossover",
  "xd-crossover-low": "Low-to-high cable crossover",
  "xd-pecdeck": "Pec deck",

  /* --- záda --- */
  "xd-pullup-under": "Chin-up",
  "xd-pullup-wide": "Wide-grip pull-up",
  "xd-db-row-one": "One-arm dumbbell row",
  "xd-tbar-row": "T-bar row",
  "xd-latpull-under": "Underhand lat pulldown",
  "xd-latpull-one": "Single-arm lat pulldown",
  "xd-machine-row": "Chest-supported machine row",
  "xd-cable-pullover": "Straight-arm cable pullover",
  "xd-inverted-row": "Inverted row",
  "xd-deadlift-db": "Dumbbell deadlift",
  "xd-hyperext": "Back extension",
  "xd-good-morning": "Good morning",
  "xd-shrug-bar": "Barbell shrug",
  "xd-shrug-db": "Dumbbell shrug",
  "xd-cable-row-one": "Single-arm cable row",

  /* --- nohy --- */
  "xd-front-squat": "Front squat",
  "xd-goblet-squat": "Goblet squat",
  "xd-hack-squat": "Hack squat",
  "xd-sumo-squat": "Sumo squat",
  "xd-legpress-one": "Single-leg press",
  "xd-leg-curl-seated": "Seated leg curl",
  "xd-leg-curl-standing": "Standing single-leg curl",
  "xd-leg-ext-one": "Single-leg extension",
  "xd-lunge-back": "Reverse lunge",
  "xd-lunge-walk": "Walking lunge",
  "xd-step-up": "Step-up",
  "xd-nordic-curl": "Nordic hamstring curl",
  "xd-calf-seated": "Seated calf raise",
  "xd-calf-legpress": "Leg press calf raise",
  "xd-hip-abduction": "Hip abduction machine",
  "xd-hip-adduction": "Hip adduction machine",
  "xd-deadlift-sumo": "Sumo deadlift",
  "xd-sissy-squat": "Sissy squat",
  "xd-glute-kickback": "Cable glute kickback",

  /* --- ramena --- */
  "xd-arnold-press": "Arnold press",
  "xd-ohp-machine": "Machine shoulder press",
  "xd-ohp-seated-bar": "Seated barbell overhead press",
  "xd-lat-raise-cable": "Cable lateral raise",
  "xd-lat-raise-machine": "Machine lateral raise",
  "xd-front-raise-db": "Dumbbell front raise",
  "xd-front-raise-plate": "Plate front raise",
  "xd-rear-fly-db": "Bent-over dumbbell reverse fly",
  "xd-reverse-pecdeck": "Reverse pec deck",
  "xd-upright-row": "Upright row",
  "xd-rear-delt-cable": "Single-arm cable rear delt fly",
  "xd-landmine-press": "Landmine press",

  /* --- biceps --- */
  "xd-curl-ez": "EZ-bar curl",
  "xd-curl-cable": "Cable curl",
  "xd-curl-concentration": "Concentration curl",
  "xd-curl-bayesian": "Bayesian cable curl",
  "xd-curl-incline": "Incline dumbbell curl",
  "xd-curl-spider": "Spider curl",
  "xd-curl-reverse": "Reverse curl",
  "xd-wrist-curl": "Wrist curl",
  "xd-preacher-machine": "Machine preacher curl",
  "xd-curl-hammer-rope": "Rope hammer curl",

  /* --- triceps --- */
  "xd-pushdown-rope": "Rope triceps pushdown",
  "xd-pushdown-reverse": "Reverse-grip pushdown",
  "xd-overhead-cable": "Overhead cable triceps extension",
  "xd-overhead-db": "Overhead dumbbell triceps extension",
  "xd-kickback-db": "Dumbbell kickback",
  "xd-kickback-cable": "Cable kickback",
  "xd-close-grip-bench": "Close-grip bench press",
  "xd-bench-dips": "Bench dip",
  "xd-triceps-machine": "Triceps press machine",
  "xd-skullcrusher": "EZ-bar skull crusher",

  /* --- core --- */
  "xd-side-plank": "Side plank",
  "xd-plank-reach": "Plank shoulder tap",
  "xd-cable-crunch": "Cable crunch",
  "xd-crunch-machine": "Machine crunch",
  "xd-russian-twist": "Russian twist",
  "xd-pallof-press": "Pallof press",
  "xd-hollow-hold": "Hollow hold",
  "xd-leg-raise-floor": "Lying leg raise",
  "xd-captains-chair": "Captain's chair leg raise",
  "xd-bicycle-crunch": "Bicycle crunch",
  "xd-ab-wheel": "Ab wheel rollout",
  "xd-woodchopper": "Cable woodchopper",
  "xd-hanging-knee-raise": "Hanging knee raise",
  "xd-v-up": "V-up"
};
